name: flutter_platform_checker
description: Shows you which platforms can be targeted by your Flutter app based on dependencies
version: 1.0.3
homepage: https://github.com/redsolver/flutter_platform_checker

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  pub_api_client: ^1.0.9
  yaml: ^3.1.0
  barbecue: ^0.2.0
  tint: ^1.0.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4

executables:
  flutter_platform_checker: flutter_platform_checker
